base_url = "https://arbs09.dev"
title = "arbs09.dev"
description = "@arbs09.dev"
compile_sass = false
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml"]
default_language = "en"
author = "arbs09"

[search]
index_format = "elasticlunr_json"

[markdown]
render_emoji = true

[link_checker]
internal_level = "warn"
external_level = "warn"

[extra]
keywords = "arbs09"